### ISSUE TITLE
Precipitación y temperatura en estaciones meteorológicas

### ISSUE THREAD

**Issue by eliocamp** [cienciadedatos/datos-de-miercoles#14]
Tengo unos datos de temperatura y precipitación en distintas estaciones de Argentina y Paraguay. Estas son las ubicaciones:

![image](https://user-images.githubusercontent.com/8617595/57265930-2ca1b300-7050-11e9-8555-c75dff4a4cae.png)

Son de la base de datos [Claris LPB ](http://www.cima.fcen.uba.ar/ClarisLPB/). ¿Les parece que es demasiado local?

**Comment by jas1** [comment]
Por mi va bien. 
lo tenes preparado tipo, con diccionario de datos, y todo junto en un csv o hay que laburarlo un toque antes ? 

asi queda el formato para presentarlo en alguna semana =)

**Comment by eliocamp** [comment]
Lo tengo en varios txt con datos para cada estación y uno con los metadatos de las estaciones. Pero tengo también el script que lee todo en dos dataframes tidy. 
Como anectoda, esta base de datos la usamos con mí novia en  prácticamente el primer proyecto que hicimos con R. Como éramos unos nabos, nuestro escrito para levantar los datos era un despelote larguísimo con un for loop horrendo. Ahora, con más sabiduría, lo levanté en dos líneas.

**Comment by eliocamp** [comment]
Los tengo en mi compu pero no sé cómo hacer para subirlos al repo. ¿Los pongo en una carpeta en datos? ¿Con qué fecha serían?

**Comment by rivaquiroga** [comment]
¡Muchas gracias @eliocamp! :avocado: :avocado:
