### ISSUE TITLE
Datos Pokemones desde Kaggle

### ISSUE THREAD

**Issue by gonzalofichero** [cienciadedatos/datos-de-miercoles#34]
Buenas.

Estoy jugando con el data set de Pokemones que subió Kaggle hace un tiempo.
Estaba pensando en traducirlo al español, ya que sólo los nombres de columnas y los tipos de pokemones necesitan ser traducidos.
Quisiera saber si están interesados en que traduzca el data set, y mi única pregunta es qué hacer cuando el nombre de un Pokemon tiene una palabra que lo "define". Por ejemplo: Pokemon 720 es HoopaHoopa Confined...

Dejo los nombres tal cual vienen? [nunca llegué a las últimas generaciones de Pokemones para saber si tiene sentido en algo esa definición en el nombre]

Abrazos!

**Comment by jas1** [comment]
Gracias por el aporte !

parece ser que , el nombre es ese. 
https://bulbapedia.bulbagarden.net/wiki/Hoopa_(Pok%C3%A9mon)

si queres agregarle una traducción lo haría en otra columna, 
que te quede "nombre_original" y "nombre_traducido"

de esa forma pdoes ir y venir entre los 2 idiomas :D sin demasiada vuelta. 
y lo dejas a eleccion del consumidor de datos =).

**Comment by jas1** [comment]
es este el dataset ?
https://www.kaggle.com/rounakbanik/pokemon

si avanzanste con alguna traduccion aunque sea de columnas, bienvenidas sean =)

**Comment by gonzalofichero** [comment]
Hola, Julio! 

Tomé los datos de acá:
https://www.kaggle.com/abcsds/pokemon

Y agregué una columna extra con el estadío de Evolución (vacío para los Pokemones de forma única), tomado de acá: https://pokemondb.net/evolution

Dejé el nombre original, y traduje yo los nombres hacia el español cuando había palabras "explicativas" del Pokemon.

Me queda finalmente el data set con los siguientes campos:

- ID_poke: ID de PokeIndex
- nombre_original: nombre tal cual viene en el desafío de Kaggle
- nombre_traducido: traducido por mí
- tipo_1: tipo Pokemon principal
- tipo_2: tipo Pokemon secundario
- total: suma de vida + ataque + defensa + velocidad
- puntos_vida
- ataque
- defensa
- velocidad_ataque
- velocidad_defensa
- velocidad
- generación: hasta 6ta generación
- es_legendario: flag VERDADERA/FALSO indicando si el Pokemon es considerado Legendario
- nivel_evolucion: 1 a 3 y nulo para los Pokemones de forma única

Me podrías indicar cómo te hago llegar el .csv? Xq acá no lo puedo attachear.

**Comment by rivaquiroga** [comment]
¡Hola @gonzalofichero! Si no te deja adjuntar el .csv acá, prueba cambiándole la extensión a .txt. Esos sí se pueden agregar a los mensajes de un _issue_.
¡Gracias por el aporte!

**Comment by gonzalofichero** [comment]
[pokemon_simple_es.txt](https://github.com/cienciadedatos/datos-de-miercoles/files/3355910/pokemon_simple_es.txt)

Va en txt! Abrazo!

**Comment by rivaquiroga** [comment]
Buenísimo!!! La próxima semana salimos con estos datos 🚀 
¡Muchas gracias!

**Comment by rivaquiroga** [comment]
@gonzalofichero: ya está listo: https://github.com/cienciadedatos/datos-de-miercoles/blob/master/datos/2019/2019-07-10/README.md
Sería genial si alcanzas a darle una mirada para ver cómo quedó. 
Lo anunciaremos durante la mañana. Puse tu cuenta de Twitter en los créditos. ¿Está bien? ¿O prefieres la de Github u otra?

**Comment by gonzalofichero** [comment]
Está perfecto! Gracias!
