### ISSUE TITLE
Link para datos

### ISSUE THREAD

**Issue by edgararuiz** [cienciadedatos/datos-de-miercoles#45]
El link en el codigo aqui tiene que ser corregido: https://github.com/cienciadedatos/datos-de-miercoles/tree/master/datos/2019/2019-07-10

Dice: pokemones <- readr::read_csv("https://raw.githubusercontent.com/cienciadedatos/datos-de-miercoles/master/datos/2019/2019-07-10/pokemon.csv")

Y tiene que ser:  pokemones <- readr::read_csv("https://raw.githubusercontent.com/cienciadedatos/datos-de-miercoles/master/datos/2019/2019-07-10/pokemones.csv")

**Comment by rivaquiroga** [comment]
¡Gracias!
