### ISSUE TITLE
registros de comercio de hispanoamérica

### ISSUE THREAD

**Issue by pachamaltese** [cienciadedatos/datos-de-miercoles#5]
Para otro miércoles podriamos usar los datos que resultan de correr el siguiente código:

```r
if (!require("pacman")) install.packages("pacman")
pacman::p_load(tradestatistics)
 
countries <- c("arg", "bol", "chl", "col", "cri", "cub", "dom", "ecu", "slv", "gtm", "hnd", "mex", "nic", "pan", "pry", "per", "ury", "ven")
 
hispanoamerica <- ots_create_tidy_data(years = 2010:2017, reporters = countries, partners = "all", include_shortnames = TRUE, include_communities = TRUE)
 
save(hispanoamerica, file = "hispanoamerica.rda", compress = "xz")
```

de allí surgen algunas preguntas interesantes
* ¿Cómo ha evolucionado el comercio entre los países de la región?
* ¿Qué % de lo que el país P exporta va al resto de la región vs resto del mundo?
* ¿Qué países se especializan en determinada categoría de producto?
* ¿Cuáles países son exportadores netos y cuáles importadores netos?
* Etc

**Comment by rivaquiroga** [comment]
Buenísimo @pachamaltese! Muchas gracias!

**Comment by jas1** [comment]
este ya salio , habria que cerrar el issue =)

**Comment by rivaquiroga** [comment]
Cerrado vía https://github.com/cienciadedatos/datos-de-miercoles/pull/11
