### ISSUE TITLE
Incendios en el Amazonas 

### ISSUE THREAD

**Issue by pmnatural** [cienciadedatos/datos-de-miercoles#57]

**Comment by pmnatural** [comment]
Si ! es unidad administrativa! Disculpa estaba en el campo y no siempre accedo bien a interent

**Comment by pmnatural** [comment]
Las noticias sobre los incendios del Amazonas han estado en los medios toda el mes pasado,y es una buena oportunidad para practicar analizarlos con R. 

---

### Los datos

---

Los incendios activos se detectan median imágenes de satélites sobre la base de anomalías termales, es decir diferencias considerables entre la temperatura de un pixel dado y las temperaturas que se registran en el terreno a su alrededor. 

El sensor MODIS,a bordo de los satélites Terra y Aqua, registra incendios en pixeles de 1 km de lado. El sensor VIIRS esta a bordo del satélite SNPP, usa un algoritmo similar para detectar incendios pero el pixel es de 375 m de lado. Debido al tamaño del pixel en el terreno, puede haber más de un foco de incendio en los datos de MODIS, pero con pocos pixeles se cubre mejor toda America Latina. 

El dataset que se presenta corresponde a 6 meses de registros de incendios activos diarios detectados por sensor MODIS tanto por el satelite Terra como por el Aqua, que en conjunto miran un misma region 4 veces por dia.

---

### Obtener los datos

---
```{r}
library(readr)
incendios <- read_csv("incendios.csv")
incendios_pais <- read_csv("incendios_pais.csv")
```
---

### Diccionario de datos

---

#### **incendios.csv**

Atributo | Descripción
-- | --
latitud | Latitud del centro del pixel (en grados decimales, WGS84)donde se detectó la anomalía de temperatura
longitud | Longitud del centro del pixel (en grados decimales, WGS84)donde se detectó la anomalía de temperatura
fecha | Fecha de adquisición del dato de incendio activo
horamin | Momento de la adquisición del dato de incendio activo en horas y minutos UTC
intensidad | Intensidad de incendio (FRP Fire Radiative Power, en megawatts)
mes | mes del año 
semana | semana del año 

#### **incendio-pais.csv**

Ademas de los atributos de incendios.csv, presenta estos adicionales:

Atributo | Descripción:
-- | --
geometry  | lista de coordenadas del punto, en formato _sf_
pais | nombre del pais
ISO |codigo ISO de 3 letras del pais

---

### Fuente de datos

Los datos fueron descargado del [servicio FIRMS de NASA](https://firms.modaps.eosdis.nasa.gov/download/) para Sudamerica y Centroamerica para el periodo , combinados en un solo archivo, permite descargar los datos de incendios activos de la ultima semana y tambien solicitar datos historicos para sectores geograficos definidos. 
Los datos fueron filtrados para presentar solo los que corresponden a vegetacion (tipo es 0) y con confianza > 0.7, seleccionando y renombrando las variables correspondientes a la posicion del incendio, la fecha y hora, e intensidad del incendio. Se agregaron los atributos de mes y semana del año para facilitar un agrupamiento temporal. 

A estos datosles agregué el nombre del pais y la sigla ISO correspondiente mediante analisis espacial, usando los paises de latinoamerica obtenidos del sitio [Natural Earth](http://www.naturalearthdata.com/)

El poligono de la cuenca Amazonica puede obtenerse de [aqui](http://worldmap.harvard.edu/data/geonode:amapoly_ivb) en distintos formatos. Yo lo bajé tanto en formato shapefile comprimido (amapoly_ivb.zip) como en geojson (amapoly_ivb.json) por si alguien quiere usarlos.

**Comment by pmnatural** [comment]
[incendios_pais.zip](https://github.com/cienciadedatos/datos-de-miercoles/files/3593201/incendios_pais.zip)

**Comment by pmnatural** [comment]
[incendios.zip](https://github.com/cienciadedatos/datos-de-miercoles/files/3593203/incendios.zip)

**Comment by rivaquiroga** [comment]
¡Buenísimo @pmnatural! Muchas gracias por tu aporte :hugs:  
El miércoles salimos con esto :rocket:

**Comment by pmnatural** [comment]
El poligono de la cuenca amazonica en formato shapefile es este:
[amapoly_ivb.zip](https://github.com/cienciadedatos/datos-de-miercoles/files/3593205/amapoly_ivb.zip)

**Comment by pmnatural** [comment]
Las visualizaciones seran mi contribucion al tweeter!

**Comment by pmnatural** [comment]
Ojo que los datos son distintos a los que habia puesto los otros dias.

**Comment by pmnatural** [comment]
Riva, hice un pequeño cambio en los datos con el pais, hay que sacar del diccionario de dato el campo geometry, porque ese no va (es molesto y va a confundir a mucha gente, estan latitud y  longitud para usar). El dataset correcto sin ese campo va aqui. 
[incendios_paisf.zip](https://github.com/cienciadedatos/datos-de-miercoles/files/3596051/incendios_paisf.zip)

**Comment by rivaquiroga** [comment]
¡Perfecto! Lo eliminamos, entonces.
¡Muchas gracias!

**Comment by rivaquiroga** [comment]
¡Listo! Publicado vía https://github.com/cienciadedatos/datos-de-miercoles/pull/61
