### ISSUE TITLE
Error con link del archivo

### ISSUE THREAD

**Issue by edgararuiz** [cienciadedatos/datos-de-miercoles#9]
En el README de esta semana el codigo para bajar los datos necesita ser corregido, actualmente dice:

`gapminder <- readr::read_csv("https://raw.githubusercontent.com/cienciadedatos/datos-de-miercoles/master/datos/2019/2019-04-23/gapminder_es.csv")`

El error esta aqui: `2019-04-23`, tiene que ser `2019-04-24`

**Comment by rivaquiroga** [comment]
¡Corregido! Muchas gracias por advertirlo.
